# Generated by Django 5.2.5 on 2025-09-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('footwear', 'Footwear'), ('kit', 'Kit'), ('shorts and pants', 'Shorts and Pants'), ('jackets and sportswear', 'Jackets and Sportswear'), ('tracksuits', 'Tracksuits'), ('others', 'Others')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
